[support]
srv-support-01 ansible_host=100.22.1.10

[ia]
srv-ia-01 ansible_host=100.22.3.10

[infra]
srv-servicios-varios-01 ansible_host=100.22.2.10
srv-devops-01 ansible_host=100.22.2.11
srv-vpn-01 ansible_host=100.22.2.12
